name: Code Review

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  review:
    name: Lint & Security Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Install ESLint
        run: npm install --save-dev eslint @eslint/js globals

      - name: Run ESLint
        run: npx eslint . --ext .js,.jsx,.ts,.tsx

      - name: Generate ESLint HTML report
        run: npx eslint . --ext .js,.jsx,.ts,.tsx -f html -o eslint-report.html

      - name: Run npm audit for vulnerabilities
        run: npm audit --audit-level=moderate || true

      - name: Upload Lint Report artifact
        uses: actions/upload-artifact@v4
        with:
           name: eslint-report
           path: eslint-report.html
